### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lanceofwhichwedream** [billykwooten/GrafanaDashboards#1]
Hey, I really like your openweather dashboard but I live in a mixed Temperature household. It'd be great if I could specify the job name for the dashboard as a variable simlar to what the Node Exporter Full dashboard provides. Thanks!

**Comment by billykwooten** [comment]
Hey @lanceofwhichwedream, apologies for almost a year without a response, I am just now seeing this issue request. This has been implemented in my new grafana v7 json graph.

https://github.com/billykwooten/GrafanaDashboards/commit/29968be58d89c0a3ce744a4bcd7a7bf18b87aa1a
